# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

parameters:
    APP_ENV: '%env(APP_ENV)%'

services:
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Akyos\CoreBundle\:
        resource: './../../*'
        tags: [ 'controller.service_arguments' ]
        public: true

    twig.extension.globals_extension:
        alias: 'Akyos\CoreBundle\Twig\GlobalsExtension'
        public: true

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: 1 }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
